version: '3'

services:
  nginx:
    image: nginx:1.10.3
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./www:/var/www
      - ./nginx.conf:/default.conf
    environment: 
      project_name: ${APP_NAME}
    working_dir:
      /var/www
    command: /bin/bash -c "envsubst '$$project_name' < /default.conf > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    links:
      - php
  
  php:
    build:
      context: ./
      dockerfile: php.Dockerfile
      args: 
        USER_ID: ${USER_ID}
    volumes:
      - ./www:/var/www
      - ./php-entry.sh:/php-entry.sh
      - ./.env:/.env
    environment: 
      APP_NAME: ${APP_NAME}
    ports:
      - 9000:9000
    depends_on:
      - database
    working_dir:
      /var/www
    user: '1000'
    entrypoint: '/php-entry.sh'
    
  database:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME} 
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

volumes:
  db:
    